version: '3'
services:
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - redisnet
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./data:/data:rw
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "
networks:
  redisnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.39.0.0/16
          gateway: 172.39.0.10
