version: '3'
services:
  redis:
    image: redis:3.0.6
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - redisnet
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./data:/data:rw
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "
networks:
  redisnet:
    driver: bridge
