version: '3.1'
services:
  db:
    image: mysql:5.7.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /u01/mysql-5.7.17/conf:/etc/mysql
      - /u01/mysql-5.7.17/data:/var/lib/mysql
      - /u01/mysql-5.7.17/logs:/var/log/mysql
      - /u01/mysql-5.7.17/run:/var/run/mysqld
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: isi%2020
networks:
  esnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16
          gateway: 172.33.0.10
